spring:
  application:
    name: tasklist
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
  security:
    jwt:
      secret: c2RucXdla2Rua3F3ZG5rcWpkbmtqcXdqcWRxZHdxZHc=
      access: 3600000
      refresh: 2592000000


  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yaml
    default-schema: tasklist

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

springdoc:
  override-with-generic-response: false

logging:
  level:
    liquibase: INFO
