spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names:
      - redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password:

  application:
    name: tasklist
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      secret: ${JWT_SECRET}
      access: 1
      refresh: 30


  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yaml
    default-schema: tasklist

server:
  port: 8090

springdoc:
  override-with-generic-response: false

logging:
  level:
    liquibase: INFO

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
